### ISSUE TITLE
What are the units for discharges and globalIrradiances?

### ISSUE THREAD

**Issue by fabianmoronzirfas** [technologiestiftung/flusshygiene#176]
Currently I'm using ["PiratenNinjas"](https://en.wikipedia.org/wiki/List_of_humorous_units_of_measurement#Pirate-ninja) which is not right.

> A Pirate-ninja is defined as one kilowatt-hour (3.6 MJ) per Martian day

**Comment by fabianmoronzirfas** [comment]
![](https://media1.giphy.com/media/SGrmNUjEHfVxC/giphy.gif)
![](https://media0.giphy.com/media/26h0oZIGGOFZdZj4Q/giphy.gif)

**Comment by wseis** [comment]
For discharge it is m³/s, for global irradiance it is W/m².

**Comment by fabianmoronzirfas** [comment]
Thank you
