### ISSUE TITLE
adding logos of funding institution and project on landing page

### ISSUE THREAD

**Issue by wseis** [technologiestiftung/flusshygiene#252]
we have to add the logo of BMBF and ReWaM funding program on our landing page. Otherwise we violate our funding obligations. While this seems unimportant at first, it is actually very important and we get in trouble if we do not do it.

Less important: Maybe we can also include a link to the involved parters at the bottom.

**Comment by fabianmoronzirfas** [comment]
Can you point me at the right resources.

- Images
- Name to add 
- link

**Comment by wseis** [comment]
Email sent with Logo files
