### ISSUE TITLE
Create Account for berliner-badestellen

### ISSUE THREAD

**Issue by fabianmoronzirfas** [technologiestiftung/flusshygiene#272]
To be able to run the berliner-badestellen predictions side by side with the old system we need another account where we have shared credentials and manage the spots that have a prediction

**Comment by fabianmoronzirfas** [comment]
@wseis @sebastian-meier is there a specific e-mail address to which we should bind this new account? If not I would create one like (berliner-badestellen@flussbaden.org) to register at auth0 and then pass the credentials on to you guys so you can setup the prediction

**Comment by wseis** [comment]
sounds good to me

**Comment by fabianmoronzirfas** [comment]
Done.
