### ISSUE TITLE
to many eager relations on bathingspot

### ISSUE THREAD

**Issue by ff6347** [technologiestiftung/flusshygiene#77]
Original by @fabianmoronzirfas

**Comment by fabianmoronzirfas** [comment]
Single bathingspot is giving also measurements. Should not be like this. See 

https://github.com/technologiestiftung/flusshygiene/blob/06a6e6b492179558063753debb1c084f9632402e/packages/postgres-api/src/lib/request-handlers/bathingspots/get.ts#L74 

Uses `findOne` instead of `QueryBuilder`
